import React, { useState } from 'react';
import { FileText, Download, Printer, Users, CreditCard, Calendar, Dumbbell, Filter, CalendarDays, User } from 'lucide-react';
import { Member, Payment, Attendance, EquipmentActivity } from './types';

interface AdminReportsProps {
  data: {
    members: Member[];
    payments: Payment[];
    attendance: Attendance[];
    equipmentActivities: EquipmentActivity[];
  };
}

export const AdminReports = ({ data }: AdminReportsProps) => {

  // Filter States
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [selectedMember, setSelectedMember] = useState('ALL');

  const generateCSV = (filename: string, headers: string[], rows: any[][]) => {
    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.map(cell => `"${String(cell || '').replace(/"/g, '""')}"`).join(','))
    ].join('\n');
    
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `${filename}_${new Date().toISOString().split('T')[0]}.csv`;
    link.click();
  };

  const printReport = (title: string, headers: string[], rows: any[][]) => {
    const printWindow = window.open('', '', 'width=800,height=800');
    if (!printWindow) {
      alert("Pop-ups are blocked. Please allow them to print.");
      return;
    }

    const tableHtml = `
      <table>
        <thead>
          <tr>${headers.map(h => `<th>${h}</th>`).join('')}</tr>
        </thead>
        <tbody>
          ${rows.map(row => `<tr>${row.map(cell => `<td>${cell || ''}</td>`).join('')}</tr>`).join('')}
        </tbody>
      </table>
    `;

    const filterText = (startDate || endDate || selectedMember !== 'ALL') 
      ? `Filters Applied - ` + 
        (selectedMember !== 'ALL' ? `Member: ${data.members.find(m => m.id === selectedMember)?.name || selectedMember} | ` : '') +
        (startDate ? `From: ${startDate} ` : '') + 
        (endDate ? `To: ${endDate}` : '')
      : 'All Records';

    printWindow.document.write(`
      <html>
        <head>
          <title>${title}</title>
          <style>
            @page { size: A4; margin: 20mm; }
            body { font-family: system-ui, sans-serif; background: #fff; margin: 0; padding: 0; color: #111; }
            .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #000; padding-bottom: 10px; }
            .title { font-size: 24px; font-weight: bold; }
            .date { font-size: 14px; color: #555; margin-top: 5px; }
            .filters { font-size: 12px; color: #666; margin-top: 5px; font-style: italic; }
            table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 12px; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            th { background-color: #f4f4f4; font-weight: bold; }
            tr:nth-child(even) { background-color: #f9f9f9; }
            .footer { text-align: center; font-size: 10px; color: #888; margin-top: 40px; }
            @media print { body { background: transparent; } }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="title">IRONPULSE GYM</div>
            <div class="date">${title} - Generated on ${new Date().toLocaleDateString()}</div>
            <div class="filters">${filterText}</div>
          </div>
          ${tableHtml}
          <div class="footer">Generated by IronPulse Gym Management System</div>
          <script>
            window.onload = () => { setTimeout(() => { window.print(); window.close(); }, 500); }
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  // --- Filtering Helpers ---
  const isDateInRange = (dateStr: string) => {
    if (!dateStr) return false;
    const date = new Date(dateStr).getTime();
    const start = startDate ? new Date(startDate).getTime() : 0;
    const end = endDate ? new Date(endDate).getTime() : Infinity;
    return date >= start && date <= end;
  };

  const isMemberMatch = (memberId: string) => {
    if (selectedMember === 'ALL') return true;
    return memberId === selectedMember;
  };

  // --- Reports Configurations ---

  const reports = [
    {
      id: 'members',
      title: 'Member Roster',
      description: 'Complete list of all gym members, contact info, and active membership status.',
      icon: Users,
      color: 'from-blue-500 to-indigo-500',
      getData: () => {
        const headers = ['ID', 'Name', 'Email', 'Phone', 'Type', 'Status', 'Joined Date'];
        let filtered = data.members.filter(m => isMemberMatch(m.id));
        if (startDate || endDate) filtered = filtered.filter(m => isDateInRange(m.joinedDate));
        
        const rows = filtered.map(m => [m.id, m.name, m.email, m.phone, m.membershipType, m.status, m.joinedDate]);
        return { headers, rows };
      }
    },
    {
      id: 'revenue',
      title: 'Financial Revenue',
      description: 'Transaction log of all payments, renewals, and due statuses.',
      icon: CreditCard,
      color: 'from-emerald-500 to-teal-500',
      getData: () => {
        const headers = ['Payment ID', 'Member', 'Plan', 'Amount ($)', 'Method', 'Status', 'Date'];
        let filtered = data.payments.filter(p => isMemberMatch(p.memberId));
        if (startDate || endDate) filtered = filtered.filter(p => isDateInRange(p.date));

        const rows = filtered.map(p => {
          const memberName = data.members.find(m => m.id === p.memberId)?.name || p.memberId;
          return [p.id, memberName, p.planName, p.amount, p.method, p.status, p.date];
        });
        return { headers, rows };
      }
    },
    {
      id: 'attendance',
      title: 'Attendance Log',
      description: 'Daily check-in and check-out records for all members.',
      icon: Calendar,
      color: 'from-purple-500 to-pink-500',
      getData: () => {
        const headers = ['Record ID', 'Member', 'Date', 'Check In', 'Check Out'];
        let filtered = data.attendance.filter(a => isMemberMatch(a.userId));
        if (startDate || endDate) filtered = filtered.filter(a => isDateInRange(a.date));

        const rows = filtered.map(a => {
          const memberName = data.members.find(m => m.id === a.userId)?.name || a.userId;
          return [a.id, memberName, a.date, a.checkIn, a.checkOut || 'Active'];
        });
        return { headers, rows };
      }
    },
    {
      id: 'equipment',
      title: 'Equipment Usage',
      description: 'Log of all active and completed equipment workout sessions.',
      icon: Dumbbell,
      color: 'from-orange-500 to-red-500',
      getData: () => {
        const headers = ['Session ID', 'Equipment Name', 'Category', 'Member', 'Date', 'Start Time', 'End Time'];
        let filtered = data.equipmentActivities.filter(a => isMemberMatch(a.member.id));
        if (startDate || endDate) filtered = filtered.filter(a => isDateInRange(a.date));

        const rows = filtered.map(a => [
          a.id, a.equipment.name, a.equipment.type, a.member.name, a.date, a.startTime, a.endTime || 'Ongoing'
        ]);
        return { headers, rows };
      }
    }
  ];

  return (
    <div className="space-y-8 pb-10">
      <div>
        <h2 className="text-3xl font-extrabold text-white mb-2 flex items-center gap-3">
          <FileText className="text-primary-400 w-8 h-8" />
          System Reports
        </h2>
        <p className="text-white/60 text-sm max-w-lg">
          Generate, download, and print comprehensive data reports for your gym's operations. Use the filters below to narrow down your report scope.
        </p>
      </div>

      {/* Global Filter Bar */}
      <div className="glass p-6 rounded-3xl border border-white/5 flex flex-col md:flex-row gap-6 items-end relative overflow-hidden shadow-xl">
        <div className="absolute top-0 right-0 p-6 opacity-10 pointer-events-none">
          <Filter className="w-32 h-32 text-primary-500" />
        </div>
        
        <div className="flex-1 w-full relative z-10">
          <label className="block text-xs font-bold text-white/50 uppercase tracking-widest mb-2 flex items-center gap-1.5">
            <User className="w-4 h-4" />
            Member Filter
          </label>
          <div className="relative">
            <select 
              value={selectedMember} 
              onChange={(e) => setSelectedMember(e.target.value)}
              className="input-field w-full bg-black/40 focus:bg-black/60 border-white/10 text-white appearance-none py-3"
            >
              <option value="ALL">All Members</option>
              {data.members.map(m => (
                <option key={m.id} value={m.id}>{m.name} ({m.membershipType})</option>
              ))}
            </select>
            <div className="absolute inset-y-0 right-4 flex items-center pointer-events-none text-white/30">
              ▼
            </div>
          </div>
        </div>

        <div className="flex-1 w-full relative z-10">
          <label className="block text-xs font-bold text-white/50 uppercase tracking-widest mb-2 flex items-center gap-1.5">
            <CalendarDays className="w-4 h-4" />
            From Date
          </label>
          <div className="relative">
            <input 
              type="date" 
              value={startDate} 
              onChange={(e) => setStartDate(e.target.value)}
              className="input-field w-full bg-black/40 focus:bg-black/60 border-white/10 [color-scheme:dark] py-3 text-white"
            />
          </div>
        </div>

        <div className="flex-1 w-full relative z-10">
          <label className="block text-xs font-bold text-white/50 uppercase tracking-widest mb-2 flex items-center gap-1.5">
            <CalendarDays className="w-4 h-4" />
            To Date
          </label>
          <div className="relative">
            <input 
              type="date" 
              value={endDate} 
              onChange={(e) => setEndDate(e.target.value)}
              className="input-field w-full bg-black/40 focus:bg-black/60 border-white/10 [color-scheme:dark] py-3 text-white"
            />
          </div>
        </div>

        <div className="relative z-10">
          <button 
            onClick={() => { setStartDate(''); setEndDate(''); setSelectedMember('ALL'); }}
            className="px-6 py-3.5 rounded-xl text-white/50 hover:text-white hover:bg-white/10 font-bold transition-colors border border-transparent hover:border-white/10 whitespace-nowrap"
          >
            Clear Filters
          </button>
        </div>
      </div>

      {/* Reports Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {reports.map((report) => {
          const Icon = report.icon;
          return (
            <div key={report.id} className="glass p-8 rounded-3xl relative overflow-hidden group border border-white/5 hover:border-white/20 transition-all shadow-xl">
              <div className={`absolute top-0 right-0 w-48 h-48 bg-gradient-to-br ${report.color} rounded-full blur-3xl opacity-10 -mr-20 -mt-20 pointer-events-none group-hover:opacity-20 transition-opacity`} />
              
              <div className="flex items-start gap-5 mb-6">
                <div className={`w-14 h-14 rounded-2xl bg-gradient-to-br ${report.color} flex items-center justify-center text-white shadow-lg`}>
                  <Icon className="w-7 h-7" />
                </div>
                <div>
                  <h3 className="text-xl font-bold text-white mb-1">{report.title}</h3>
                  <p className="text-white/50 text-sm leading-relaxed">{report.description}</p>
                </div>
              </div>

              <div className="flex gap-3 mt-8 relative z-10">
                <button 
                  onClick={() => {
                    const { headers, rows } = report.getData();
                    generateCSV(report.title.replace(/\s+/g, '_').toLowerCase(), headers, rows);
                  }}
                  className="flex-1 py-3.5 rounded-xl bg-white/5 hover:bg-white/10 text-white font-bold flex items-center justify-center gap-2 border border-white/10 transition-colors"
                >
                  <Download className="w-5 h-5" />
                  CSV
                </button>
                <button 
                  onClick={() => {
                    const { headers, rows } = report.getData();
                    printReport(report.title, headers, rows);
                  }}
                  className="flex-1 py-3.5 rounded-xl bg-primary-600 hover:bg-primary-500 text-white font-bold flex items-center justify-center gap-2 shadow-lg shadow-primary-500/20 transition-all"
                >
                  <Printer className="w-5 h-5" />
                  Print PDF
                </button>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
